### ISSUE TITLE
Displaying Association

### ISSUE THREAD

**Issue by RamiBH** [mendix/TreeViewAndGridView#33]
Hi,

I am trying to use the grid view widget in displaying an attribute that is two associations from the main object.
Example: The entity type is 'ProjectMember' and the rendered attribute value is 'ProjectMember -> Employee -> Organization/Name'. The widget mentions that there are items available, however no records are displayed.

I have noticed that the widget causes an error if the "Use Database" option is set to Yes, I have to set it to No for the widget to work.

I am using version 6.10.3

Best regards and thanks,
**Rami Bou Hadir**

**Comment by JelteMX** [comment]
Can you test [this version](https://github.com/mendix/TreeViewAndGridView/raw/bugfix/async_commons_getobjectattr/dist/TreeView.mpk) for me? I haven't updated this widget in a long time, mainly because it is not actively maintained and supported by Mendix. Nevertheless, associations should now render correctly.

**Comment by JelteMX** [comment]
Fixed in [4.5.0](https://github.com/mendix/TreeViewAndGridView/releases/tag/v4.5.0)
