### ISSUE TITLE
Not working in Mendix 7.2.0

### ISSUE THREAD

**Issue by OlafJoppe** [mendix/TreeViewAndGridView#34]
Displaying a hierarchy with the treeview widget in a Mendix v7.2.0 project throws an error in the browser's console "Error: Cannot read property 'set' of undefined". Widget's version used is 4.4.

Please find attached sample mda-project.

[TreeView-v7.2.zip](https://github.com/mendix/TreeViewAndGridView/files/1019971/TreeView-v7.2.zip)

**Comment by WillemUXMendix** [comment]
it works in 7.3.0 for some reason.

**Comment by swkruger** [comment]
The same issue is experienced with the GridView in Mx v7.1.1

**Comment by JelteMX** [comment]
In Mendix 7 some methods are deprecated. `dojo.html` is the problem here. Can you check [this version](https://github.com/mendix/TreeViewAndGridView/raw/bugfix/async_commons_getobjectattr/dist/TreeView.mpk) for me? I have updated the code to fix a few issues we have while using it in a MX6 project. These changes should make it work in Mendix 7 (I tested it myself in 7.5.1)
